import { MainLayout } from 'layouts/main'
import { getSession, GetSessionParams } from 'next-auth/react'
import Head from 'next/head'

export async function getServerSideProps(
  context: GetSessionParams | undefined,
) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}

const Task = () => {
  return (
    <MainLayout>
      <Head>
        <title>Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>
      <main>Task</main>
    </MainLayout>
  )
}

export default Task
