import { MainLayout } from 'layouts/main'
import Head from 'next/head'
import Image from 'next/image'

import { useSession, signOut } from 'next-auth/react'

import { useRouter } from 'next/router'
import { LandingHeader } from 'components/Header/landing'
import { Card, Grid, Heading } from '@chakra-ui/react'

import noteListPic from '/public/note_list.svg'
import reminderPic from '/public/reminder.svg'

export default function Home() {
  const { data: session } = useSession()

  if (session) {
    return (
      <MainLayout>
        <Head>
          <title>Login</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/asignacion.png' />
        </Head>
        Signed in as {session.user?.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </MainLayout>
    )
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>

      <LandingHeader></LandingHeader>
      <Grid templateColumns='repeat(2, 1fr)' gap={6}>
        <Card>
          <Heading>Free Task</Heading>
        </Card>
        <Image
          src={noteListPic}
          alt='note'
          style={{ transform: 'scaleX(-1)' }}
        />
      </Grid>
    </>
  )
}
