import { MainLayout } from 'layouts/main'
import Head from 'next/head'

import { useSession, signIn, signOut } from 'next-auth/react'

import { useRouter } from 'next/router'
import { LandingHeader } from 'components/Header/landing'

export default function Home() {
  const { data: session } = useSession()
  const router = useRouter()

  if (session) {
    return (
      <MainLayout>
        <Head>
          <title>Login</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/asignacion.png' />
        </Head>
        Signed in as {session.user?.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </MainLayout>
    )
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>
      <LandingHeader></LandingHeader>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
      <button onClick={() => router.push('/signup')}>Sign up</button>
    </>
  )
}
