import type { NextPage } from 'next'
import NextLink from 'next/link'
import Head from 'next/head'

import {
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
  Select,
  Button,
  Center,
  Card,
  chakra,
  Heading,
  Link,
} from '@chakra-ui/react'

const Signup: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>

      <chakra.header
        display='flex'
        justifyContent='space-between'
        alignItems='center'
        bg='#09f'
        boxShadow='lg'
        p={3}
        mb={3}>
        <Link
          as={NextLink}
          href='/'
          fontSize='lg'
          fontWeight='bold'
          _hover={{ textDecoration: 'none' }}>
          <Heading>Free Task</Heading>
        </Link>

        <>
          <Link as={NextLink} href='/api/auth/signin' fontWeight='bold'>
            Sign In
          </Link>

          {/* <Button
            onClick={toggleColorMode}
            background='whiteAlpha.400'
            boxShadow='2xl'>
            {colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          </Button> */}
        </>
      </chakra.header>

      <Center h='calc(100vh - 80px)'>
        <Card p='6' w='clamp(270px,50%, 400px)'>
          <FormControl>
            <FormLabel>Name</FormLabel>
            <Input type='text' />

            <FormLabel>Email address</FormLabel>
            <Input type='email' />

            <FormLabel>Password</FormLabel>
            <Input type='password' />

            <FormLabel>Role</FormLabel>
            <Select>
              <option value='admin'>Admin</option>
              <option value='edit'>Edit</option>
              <option value='read'>Read</option>
            </Select>

            <Center mt='4'>
              <Button bg='#09f' type='submit'>
                Sign Up
              </Button>
            </Center>
          </FormControl>
        </Card>
      </Center>
    </>
  )
}

export default Signup
