import { MainLayout } from 'layouts/main'
import Head from 'next/head'

const Notes = () => {
  return (
    <MainLayout>
      <Head>
        <title>Notes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>
      <main>Notes</main>
    </MainLayout>
  )
}

export default Notes
