import Head from 'next/head'
import { MainLayout } from 'layouts/main'
import { NotesList } from 'components/Notes/List'
import { iNotes } from 'utils/interefaces/notes'
import { Box, Button, Text, Grid, useMediaQuery } from '@chakra-ui/react'
import { useState } from 'react'
import { FormToNotes } from 'components/Notes/Form'

import { AddButton } from 'components/AddButton'
import { getSession, GetSessionParams } from 'next-auth/react'
import { AddIcon } from '@chakra-ui/icons'

export async function getServerSideProps(
  context: GetSessionParams | undefined,
) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}

const data: iNotes[] = [
  {
    id: 1,
    title: 'Tarea',
    description: 'bum',
    characters: 3,
    createdAt: Date.now(),
    userId: 1,
    folderId: 2,
  },
  {
    id: 2,
    title: 'task',
    description: 'fin fan fun',
    characters: 11,
    createdAt: Date.now(),
    userId: 2,
    folderId: 2,
  },
  {
    id: 3,
    title: 'Aja',
    description: 'katum',
    characters: 5,
    createdAt: Date.now(),
    userId: 3,
    folderId: 2,
  },
  {
    id: 4,
    title: 'Tam',
    characters: 3,
    createdAt: Date.now(),
    userId: 3,
    folderId: 2,
  },
]

const Notes = () => {
  const [showForm, setShowForm] = useState(false)
  const [isLessThan800] = useMediaQuery('(max-width: 760px)', {
    ssr: true,
    fallback: false, // return false on the server, and re-evaluate on the client side
  })

  const addNotesForm = () => {
    setShowForm(true)
  }

  return (
    <MainLayout>
      <Head>
        <title>Notes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>

      <main>
        {!showForm ? (
          <Box px={5}>
            {!isLessThan800 && (
              <Button
                bg='#09f'
                _hover={{ background: '#06f' }}
                color='white'
                fontSize='lg'
                rightIcon={<AddIcon />}
                mb='3'
                onClick={addNotesForm}>
                Create
              </Button>
            )}

            {data.length > 0 ? (
              <Grid
                id='characters_grid'
                templateColumns='repeat(auto-fit, minmax(min(100%, 22rem), 1fr))'
                gap={2}>
                {data.map((note) => {
                  return <NotesList key={note.id} note={note} />
                })}
              </Grid>
            ) : (
              <Text textAlign='center' fontSize='lg'>
                No Notes, try to create a new one.
              </Text>
            )}

            {isLessThan800 && <AddButton handleAdd={addNotesForm} />}
          </Box>
        ) : (
          <FormToNotes setShowForm={setShowForm} />
        )}
      </main>
    </MainLayout>
  )
}

export default Notes
