import Head from 'next/head'
import { MainLayout } from 'layouts/main'
import { NotesList } from 'components/Notes/List'
import { iNotes } from 'utils/interefaces/notes'
import { Grid, Button, Flex } from '@chakra-ui/react'
import { useState } from 'react'
import { FormToNotes } from 'components/Notes/Form'

import { AddButton } from 'components/AddButton'
import { getSession, GetSessionParams } from 'next-auth/react'

export async function getServerSideProps(
  context: GetSessionParams | undefined,
) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}

const data: iNotes[] = [
  {
    id: 1,
    title: 'Tarea',
    description: 'bum',
    characters: 3,
    createdAt: Date.now(),
    userId: 1,
    folderId: 2,
  },
  {
    id: 2,
    title: 'task',
    description: 'fin fan fun',
    characters: 11,
    createdAt: Date.now(),
    userId: 2,
    folderId: 2,
  },
  {
    id: 3,
    title: 'Aja',
    description: 'katum',
    characters: 5,
    createdAt: Date.now(),
    userId: 3,
    folderId: 2,
  },
]

const Notes = () => {
  const [showForm, setShowForm] = useState(false)

  const addNotesForm = () => {
    setShowForm(true)
  }

  console.log({ showForm })

  return (
    <MainLayout>
      <Head>
        <title>Notes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/asignacion.png' />
      </Head>

      <main>
        {!showForm ? (
          <>
            <Grid
              id='characters_grid'
              templateColumns='repeat(auto-fit, minmax(min(100%, 22rem), 1fr))'
              gap={2}
              px={5}>
              {data.map((note) => {
                return <NotesList key={note.id} note={note} />
              })}
            </Grid>

            <AddButton handleAdd={addNotesForm} />
          </>
        ) : (
          <FormToNotes setShowForm={setShowForm} />
        )}
      </main>
    </MainLayout>
  )
}

export default Notes
